/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 model2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model2.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={3.666}>
        <mesh geometry={nodes.BottleGlass.geometry} material={materials['Glass.002']} position={[-0.049, 0, 0]} />
        <mesh geometry={nodes.Glass_1.geometry} material={materials['Glass.001']} position={[-0.015, 0, 0]} rotation={[0, 0.155, 0]} />
        <mesh geometry={nodes.Glass_2.geometry} material={materials['Glass.001']} position={[-0.1, 0, 0]} rotation={[0, 0.155, 0]} />
        <mesh geometry={nodes.Glass_Water_1.geometry} material={materials['Water.001']} position={[-0.015, 0, 0]} rotation={[0, 0.155, 0]} />
        <mesh geometry={nodes.Glass_Water_2.geometry} material={materials['Water.001']} position={[-0.1, 0, 0]} rotation={[0, 0.155, 0]} />
        <mesh geometry={nodes.Plastic_White_Stopper.geometry} material={materials['White Plastic']} position={[-0.049, 0, 0]} />
        <mesh geometry={nodes.Water.geometry} material={materials.Water} position={[-0.049, 0, 0]} />
        <mesh geometry={nodes.Wire_holder.geometry} material={materials['Metal Grey']} position={[-0.049, 0, 0]} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['Patterned paving']} scale={1.688} />
    </group>
  )
}

useGLTF.preload('/model2.gltf')
